version: '3.9'
services:
  db:
    image: mysql:8.0.28
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: gds.2015
      MYSQL_USER: docker
      MYSQL_PASSWORD: gds.2015
      MYSQL_DATABASE: rest_with_spring_boot
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - gdarlan-network
  rest-with-spring-boot-gdarlan:
    image: gadarlan/rest-with-spring-boot-gdarlan
    restart: always
    build: ./rest-with-spring-boot-and-kotlin-gabriel-darlan
    working_dir: /rest-with-spring-boot-and-kotlin-gabriel-darlan
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/rest_with_spring_boot?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: gds.2015
    ports:
      - 80:80
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - gdarlan-network
networks:
  gdarlan-network:
    driver: bridge